[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "http://localhost:8889"

[dev]
  command = "npm run dev"
  port = 8889
  targetPort = 3000
  framework = "next"

[[redirects]]
  from = "/auth/callback"
  to = "/auth/callback"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 